### ISSUE TITLE
Adhere to the LANDRegistry encode/decode specification

### ISSUE THREAD

**Issue by NicoSantangelo** [decentraland/commons#27]
Specification found here: https://github.com/decentraland/marketplace/issues/10

We're currenly not supporting strings with `, ` inside of them because the implementation does not enforce wrapping strings with `""`.
We should also enforce the max length of `name` and `description`

**Comment by abarmat** [comment]
I think the only thing left to close this issue is to enforce length on the name and description.

**Comment by NicoSantangelo** [comment]
https://github.com/decentraland/commons/blob/master/src/contracts/LANDRegistry.js#L41 🎉  !
