### ISSUE TITLE
Add docs as gh-pages

### ISSUE THREAD

**Issue by NicoSantangelo** [decentraland/commons#5]
I think it might be useful to have the doc html pages deployed as GH pages.

To do this we should serve the result of running `npm run docs`, which saves everything on a `out` folder. We'll also need to update it with every tag (or major change)

It looks like this:
![image](https://user-images.githubusercontent.com/692077/33069363-9dd2e6dc-ceb4-11e7-8761-2fd52055a175.png)

What do you think?

**Comment by eordano** [comment]
https://decentraland.github.io/commons/eth.html
