### ISSUE TITLE
Trying to connect without contracts

### ISSUE THREAD

**Issue by nachomazzara** [decentraland/commons#9]
[connect](https://github.com/decentraland/commons/blob/master/src/ethereum/eth.js#L31) will throw an error if `contracts` parameter is undefined. 

It would be great to set a default empty array at the method firm:
`async connect(defaultAccount, contracts = [], options = {})`

Or check if contracts are undefined [here](https://github.com/decentraland/commons/blob/master/src/ethereum/eth.js#L95) before looping them.

The motivation is to call `eth.connect()`

**Comment by NicoSantangelo** [comment]
Totally agree.
Will tackle on 2.2.3.

**Comment by NicoSantangelo** [comment]
All done!
[2.2.3](https://github.com/decentraland/commons/commit/b501b7cfffe7a016dc8481d63b875e7cb1fb1c23) is live
